# Generated by Django 3.0.5 on 2020-05-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIF', models.CharField(max_length=9)),
                ('empresa', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=40)),
                ('tipo_componentes', models.ManyToManyField(to='companiAPP.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('datos_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companiAPP.Cliente')),
                ('productos', models.ManyToManyField(to='companiAPP.Productos')),
            ],
        ),
    ]
